-- Generated by scripts/generate-foundation-guards.mjs; triggers are reviewed SQL.
ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_status_valid" CHECK (status IN ('draft', 'active', 'closed'));
--> statement-breakpoint
ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
CREATE INDEX "academic_years_fk_1_idx" ON "academic_years" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "academic_years_fk_2_idx" ON "academic_years" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "account_fk_1_idx" ON "account" ("userId");
--> statement-breakpoint
ALTER TABLE "audit_actors" ADD CONSTRAINT "audit_actors_actor_code_nonblank" CHECK (length(trim("actor_code")) > 0);
--> statement-breakpoint
CREATE INDEX "audit_actors_fk_1_idx" ON "audit_actors" ("user_id");
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_event_type_nonblank" CHECK (length(trim("event_type")) > 0);
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_resource_type_nonblank" CHECK (length(trim("resource_type")) > 0);
--> statement-breakpoint
CREATE INDEX "audit_events_fk_1_idx" ON "audit_events" ("school_id", "membership_id");
--> statement-breakpoint
ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_status_valid" CHECK (status IN ('active', 'closed'));
--> statement-breakpoint
ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_label_nonblank" CHECK (length(trim("label")) > 0);
--> statement-breakpoint
CREATE INDEX "class_groups_fk_1_idx" ON "class_groups" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "class_groups_fk_2_idx" ON "class_groups" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "class_groups_fk_3_idx" ON "class_groups" ("grade_id");
--> statement-breakpoint
ALTER TABLE "class_placements" ADD CONSTRAINT "class_placements_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
CREATE INDEX "class_placements_fk_1_idx" ON "class_placements" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "class_placements_fk_2_idx" ON "class_placements" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "class_placements_fk_3_idx" ON "class_placements" ("school_id", "enrolment_id", "academic_year_id", "grade_id");
--> statement-breakpoint
CREATE INDEX "class_placements_fk_4_idx" ON "class_placements" ("school_id", "class_group_id", "academic_year_id", "grade_id");
--> statement-breakpoint
ALTER TABLE "grades" ADD CONSTRAINT "grades_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "grades" ADD CONSTRAINT "grades_curriculum_code_nonblank" CHECK (length(trim("curriculum_code")) > 0);
--> statement-breakpoint
ALTER TABLE "grades" ADD CONSTRAINT "grades_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
ALTER TABLE "grades" ADD CONSTRAINT "grades_label_nonblank" CHECK (length(trim("label")) > 0);
--> statement-breakpoint
CREATE INDEX "grades_fk_1_idx" ON "grades" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "grades_fk_2_idx" ON "grades" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "learner_admissions" ADD CONSTRAINT "learner_admissions_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "learner_admissions" ADD CONSTRAINT "learner_admissions_status_valid" CHECK (status IN ('active', 'closed'));
--> statement-breakpoint
ALTER TABLE "learner_admissions" ADD CONSTRAINT "learner_admissions_admission_number_nonblank" CHECK (length(trim("admission_number")) > 0);
--> statement-breakpoint
CREATE INDEX "learner_admissions_fk_1_idx" ON "learner_admissions" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learner_admissions_fk_2_idx" ON "learner_admissions" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "learner_enrolments" ADD CONSTRAINT "learner_enrolments_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "learner_enrolments" ADD CONSTRAINT "learner_enrolments_status_valid" CHECK (status IN ('active', 'withdrawn', 'completed'));
--> statement-breakpoint
CREATE INDEX "learner_enrolments_fk_1_idx" ON "learner_enrolments" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learner_enrolments_fk_2_idx" ON "learner_enrolments" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learner_enrolments_fk_3_idx" ON "learner_enrolments" ("grade_id");
--> statement-breakpoint
CREATE INDEX "learner_enrolments_fk_4_idx" ON "learner_enrolments" ("school_id", "admission_id", "learner_id");
--> statement-breakpoint
ALTER TABLE "learner_subject_enrolments" ADD CONSTRAINT "learner_subject_enrolments_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "learner_subject_enrolments" ADD CONSTRAINT "learner_subject_enrolments_status_valid" CHECK (status IN ('active', 'withdrawn', 'completed'));
--> statement-breakpoint
CREATE INDEX "learner_subject_enrolments_fk_1_idx" ON "learner_subject_enrolments" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learner_subject_enrolments_fk_2_idx" ON "learner_subject_enrolments" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learner_subject_enrolments_fk_3_idx" ON "learner_subject_enrolments" ("school_id", "placement_id", "enrolment_id", "class_group_id", "academic_year_id", "grade_id");
--> statement-breakpoint
CREATE INDEX "learner_subject_enrolments_fk_4_idx" ON "learner_subject_enrolments" ("school_id", "offering_id", "class_group_id", "academic_year_id", "grade_id");
--> statement-breakpoint
ALTER TABLE "learners" ADD CONSTRAINT "learners_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "learners" ADD CONSTRAINT "learners_status_valid" CHECK (status IN ('active', 'left', 'completed', 'archived'));
--> statement-breakpoint
ALTER TABLE "learners" ADD CONSTRAINT "learners_display_name_nonblank" CHECK (length(trim("display_name")) > 0);
--> statement-breakpoint
CREATE INDEX "learners_fk_1_idx" ON "learners" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learners_fk_2_idx" ON "learners" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "learners_fk_3_idx" ON "learners" ("school_id", "login_membership_id");
--> statement-breakpoint
ALTER TABLE "membership_roles" ADD CONSTRAINT "membership_roles_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
CREATE INDEX "membership_roles_fk_1_idx" ON "membership_roles" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "membership_roles_fk_2_idx" ON "membership_roles" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "membership_roles_fk_3_idx" ON "membership_roles" ("role_id");
--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "roles_name_nonblank" CHECK (length(trim("name")) > 0);
--> statement-breakpoint
CREATE INDEX "roles_fk_1_idx" ON "roles" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "roles_fk_2_idx" ON "roles" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "school_memberships" ADD CONSTRAINT "school_memberships_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "school_memberships" ADD CONSTRAINT "school_memberships_status_valid" CHECK (status IN ('invited', 'active', 'suspended', 'left'));
--> statement-breakpoint
CREATE INDEX "school_memberships_fk_1_idx" ON "school_memberships" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "school_memberships_fk_2_idx" ON "school_memberships" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "school_subjects" ADD CONSTRAINT "school_subjects_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "school_subjects" ADD CONSTRAINT "school_subjects_local_code_nonblank" CHECK (length(trim("local_code")) > 0);
--> statement-breakpoint
ALTER TABLE "school_subjects" ADD CONSTRAINT "school_subjects_display_name_nonblank" CHECK (length(trim("display_name")) > 0);
--> statement-breakpoint
CREATE INDEX "school_subjects_fk_1_idx" ON "school_subjects" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "school_subjects_fk_2_idx" ON "school_subjects" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "school_subjects_fk_3_idx" ON "school_subjects" ("subject_id");
--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_status_valid" CHECK (status IN ('active', 'suspended', 'archived'));
--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_name_nonblank" CHECK (length(trim("name")) > 0);
--> statement-breakpoint
ALTER TABLE "schools" ADD CONSTRAINT "schools_timezone_nonblank" CHECK (length(trim("timezone")) > 0);
--> statement-breakpoint
CREATE INDEX "schools_fk_1_idx" ON "schools" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "schools_fk_2_idx" ON "schools" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "session_fk_1_idx" ON "session" ("userId");
--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD CONSTRAINT "staff_profiles_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD CONSTRAINT "staff_profiles_status_valid" CHECK (status IN ('active', 'inactive'));
--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD CONSTRAINT "staff_profiles_staff_code_nonblank" CHECK (length(trim("staff_code")) > 0);
--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD CONSTRAINT "staff_profiles_display_name_nonblank" CHECK (length(trim("display_name")) > 0);
--> statement-breakpoint
CREATE INDEX "staff_profiles_fk_1_idx" ON "staff_profiles" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "staff_profiles_fk_2_idx" ON "staff_profiles" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "subject_catalogue" ADD CONSTRAINT "subject_catalogue_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "subject_catalogue" ADD CONSTRAINT "subject_catalogue_status_valid" CHECK (status IN ('active', 'retired'));
--> statement-breakpoint
ALTER TABLE "subject_catalogue" ADD CONSTRAINT "subject_catalogue_curriculum_code_nonblank" CHECK (length(trim("curriculum_code")) > 0);
--> statement-breakpoint
ALTER TABLE "subject_catalogue" ADD CONSTRAINT "subject_catalogue_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
ALTER TABLE "subject_catalogue" ADD CONSTRAINT "subject_catalogue_name_nonblank" CHECK (length(trim("name")) > 0);
--> statement-breakpoint
CREATE INDEX "subject_catalogue_fk_1_idx" ON "subject_catalogue" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "subject_catalogue_fk_2_idx" ON "subject_catalogue" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "subject_grades" ADD CONSTRAINT "subject_grades_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
CREATE INDEX "subject_grades_fk_1_idx" ON "subject_grades" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "subject_grades_fk_2_idx" ON "subject_grades" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "subject_offerings" ADD CONSTRAINT "subject_offerings_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "subject_offerings" ADD CONSTRAINT "subject_offerings_status_valid" CHECK (status IN ('active', 'closed'));
--> statement-breakpoint
CREATE INDEX "subject_offerings_fk_1_idx" ON "subject_offerings" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "subject_offerings_fk_2_idx" ON "subject_offerings" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX "subject_offerings_fk_3_idx" ON "subject_offerings" ("school_id", "school_subject_id", "subject_id");
--> statement-breakpoint
CREATE INDEX "subject_offerings_fk_4_idx" ON "subject_offerings" ("school_id", "class_group_id", "academic_year_id", "grade_id");
--> statement-breakpoint
CREATE INDEX "subject_offerings_fk_5_idx" ON "subject_offerings" ("subject_id", "grade_id");
--> statement-breakpoint
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_status_valid" CHECK (status IN ('active', 'ended', 'revoked'));
--> statement-breakpoint
CREATE INDEX "teacher_assignments_fk_1_idx" ON "teacher_assignments" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "teacher_assignments_fk_2_idx" ON "teacher_assignments" ("updated_by_actor_id");
--> statement-breakpoint
ALTER TABLE "terms" ADD CONSTRAINT "terms_version_positive" CHECK (row_version > 0);
--> statement-breakpoint
ALTER TABLE "terms" ADD CONSTRAINT "terms_code_nonblank" CHECK (length(trim("code")) > 0);
--> statement-breakpoint
CREATE INDEX "terms_fk_1_idx" ON "terms" ("created_by_actor_id");
--> statement-breakpoint
CREATE INDEX "terms_fk_2_idx" ON "terms" ("updated_by_actor_id");
--> statement-breakpoint
CREATE INDEX session_expires_idx ON session ("expiresAt");
--> statement-breakpoint
CREATE INDEX verification_identifier_idx ON verification (identifier);
--> statement-breakpoint
CREATE INDEX verification_expires_idx ON verification ("expiresAt");
--> statement-breakpoint
-- No extensions required. Dates are inclusive; a transfer starts the day after
-- the previous placement ends. Role grants use half-open timestamp intervals.
CREATE FUNCTION foundation_mutable_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE school uuid; actor uuid; actor_user text;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.id <> OLD.id OR NEW.created_at <> OLD.created_at OR NEW.created_by_actor_id <> OLD.created_by_actor_id THEN
      RAISE EXCEPTION 'Immutable identity/provenance' USING ERRCODE = '23514';
    END IF;
    IF to_jsonb(NEW)->>'school_id' IS DISTINCT FROM to_jsonb(OLD)->>'school_id' THEN
      RAISE EXCEPTION 'Cannot change tenant' USING ERRCODE = '23514';
    END IF;
    NEW.row_version := OLD.row_version + 1;
    NEW.updated_at := clock_timestamp();
  END IF;
  school := (to_jsonb(NEW)->>'school_id')::uuid;
  IF school IS NOT NULL THEN
    -- Serializes temporal writes per school. Services additionally use SERIALIZABLE.
    PERFORM 1 FROM schools WHERE id = school FOR UPDATE;
  END IF;
  FOREACH actor IN ARRAY CASE WHEN TG_OP = 'INSERT' THEN ARRAY[NEW.created_by_actor_id, NEW.updated_by_actor_id] ELSE ARRAY[NEW.updated_by_actor_id] END LOOP
    SELECT user_id INTO actor_user FROM audit_actors WHERE id = actor;
    IF actor_user IS NOT NULL AND (school IS NULL OR NOT EXISTS (
      SELECT 1 FROM school_memberships WHERE school_id = school AND user_id = actor_user
        AND status = 'active' AND archived_at IS NULL AND joined_at <= now() AND ended_at IS NULL
    )) THEN
      RAISE EXCEPTION 'Actor is outside active school membership' USING ERRCODE = '23514';
    END IF;
  END LOOP;
  RETURN NEW;
END $$;
--> statement-breakpoint
CREATE FUNCTION foundation_immutable_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Append-only history' USING ERRCODE = '23514'; END $$;
--> statement-breakpoint
CREATE FUNCTION foundation_validate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM schools s WHERE NOT EXISTS (SELECT 1 FROM pg_timezone_names z WHERE z.name = s.timezone)) THEN
    RAISE EXCEPTION 'Invalid school timezone' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM membership_roles m JOIN roles r ON r.id = m.role_id WHERE r.scope <> 'school') THEN
    RAISE EXCEPTION 'Platform role cannot grant school access' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM subject_grades sg JOIN grades g ON g.id = sg.grade_id JOIN subject_catalogue s ON s.id = sg.subject_id WHERE g.curriculum_code <> s.curriculum_code) THEN
    RAISE EXCEPTION 'Subject and grade curriculum mismatch' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM academic_years a JOIN academic_years b ON a.school_id = b.school_id AND a.id < b.id WHERE a.status = 'active' AND b.status = 'active' AND daterange(a.starts_on,a.ends_on,'[]') && daterange(b.starts_on,b.ends_on,'[]')) THEN
    RAISE EXCEPTION 'Overlapping active academic years' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM terms t JOIN academic_years y ON y.id = t.academic_year_id WHERE t.starts_on < y.starts_on OR t.ends_on > y.ends_on) OR EXISTS (
    SELECT 1 FROM terms a JOIN terms b ON a.school_id = b.school_id AND a.academic_year_id = b.academic_year_id AND a.id < b.id WHERE daterange(a.starts_on,a.ends_on,'[]') && daterange(b.starts_on,b.ends_on,'[]')
  ) THEN RAISE EXCEPTION 'Terms must fit year without overlap' USING ERRCODE = '23514'; END IF;
  IF EXISTS (SELECT 1 FROM learner_enrolments e JOIN learner_admissions a ON a.id = e.admission_id JOIN academic_years y ON y.id = e.academic_year_id
    WHERE e.starts_on < greatest(a.admitted_on,y.starts_on) OR coalesce(e.ends_on,y.ends_on) > least(coalesce(a.left_on,y.ends_on),y.ends_on)) THEN
    RAISE EXCEPTION 'Enrolment outside admission or year' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM class_placements p JOIN learner_enrolments e ON e.id = p.enrolment_id JOIN academic_years y ON y.id = e.academic_year_id
    WHERE p.starts_on < e.starts_on OR coalesce(p.ends_on,y.ends_on) > coalesce(e.ends_on,y.ends_on)) THEN
    RAISE EXCEPTION 'Placement outside enrolment' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM class_placements a JOIN class_placements b ON a.school_id = b.school_id AND a.enrolment_id = b.enrolment_id AND a.id < b.id
    WHERE daterange(a.starts_on,a.ends_on,'[]') && daterange(b.starts_on,b.ends_on,'[]')) THEN
    RAISE EXCEPTION 'Overlapping class placements' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM learner_subject_enrolments s JOIN class_placements p ON p.id = s.placement_id JOIN academic_years y ON y.id = p.academic_year_id
    WHERE s.starts_on < p.starts_on OR coalesce(s.ends_on,y.ends_on) > coalesce(p.ends_on,y.ends_on)) THEN
    RAISE EXCEPTION 'Subject enrolment outside placement' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM learner_subject_enrolments a JOIN learner_subject_enrolments b ON a.school_id = b.school_id AND a.enrolment_id = b.enrolment_id AND a.offering_id = b.offering_id AND a.id < b.id
    WHERE daterange(a.starts_on,a.ends_on,'[]') && daterange(b.starts_on,b.ends_on,'[]')) THEN
    RAISE EXCEPTION 'Overlapping subject enrolments' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM teacher_assignments a JOIN teacher_assignments b ON a.school_id = b.school_id AND a.staff_id = b.staff_id AND a.offering_id = b.offering_id AND a.id < b.id
    WHERE a.status <> 'revoked' AND b.status <> 'revoked' AND daterange(a.starts_on,a.ends_on,'[]') && daterange(b.starts_on,b.ends_on,'[]')) THEN
    RAISE EXCEPTION 'Overlapping teacher assignments' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM teacher_assignments t JOIN subject_offerings o ON o.id = t.offering_id JOIN academic_years y ON y.id = o.academic_year_id
    WHERE t.starts_on < y.starts_on OR coalesce(t.ends_on,y.ends_on) > y.ends_on) THEN
    RAISE EXCEPTION 'Teacher assignment outside year' USING ERRCODE = '23514';
  END IF;
  IF EXISTS (SELECT 1 FROM membership_roles a JOIN membership_roles b ON a.school_id = b.school_id AND a.membership_id = b.membership_id AND a.role_id = b.role_id AND a.id < b.id
    WHERE a.revoked_at IS NULL AND b.revoked_at IS NULL AND tstzrange(a.valid_from,a.valid_until,'[)') && tstzrange(b.valid_from,b.valid_until,'[)')) THEN
    RAISE EXCEPTION 'Overlapping role grants' USING ERRCODE = '23514';
  END IF;
  RETURN NULL;
END $$;
--> statement-breakpoint
CREATE FUNCTION foundation_audit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE actor_user text;
BEGIN
  SELECT user_id INTO actor_user FROM audit_actors WHERE id = NEW.actor_id;
  IF actor_user IS NOT NULL AND NEW.school_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM school_memberships WHERE id = NEW.membership_id AND school_id = NEW.school_id AND user_id = actor_user AND status = 'active' AND archived_at IS NULL
  ) THEN RAISE EXCEPTION 'Audit actor/membership mismatch' USING ERRCODE = '23514'; END IF;
  IF jsonb_typeof(NEW.safe_changes) <> 'object' OR octet_length(NEW.safe_changes::text) > 8192 THEN
    RAISE EXCEPTION 'Audit payload must be a bounded safe object' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;
--> statement-breakpoint
DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.columns WHERE table_schema = 'public' AND column_name = 'row_version' LOOP
    EXECUTE format('CREATE TRIGGER mutable_guard BEFORE INSERT OR UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION foundation_mutable_guard()', t);
    EXECUTE format('CREATE CONSTRAINT TRIGGER foundation_integrity AFTER INSERT OR UPDATE OR DELETE ON %I DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION foundation_validate()', t);
  END LOOP;
END $$;
--> statement-breakpoint
CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_events FOR EACH STATEMENT EXECUTE FUNCTION foundation_immutable_guard();
--> statement-breakpoint
CREATE TRIGGER actor_append_only BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_actors FOR EACH STATEMENT EXECUTE FUNCTION foundation_immutable_guard();
--> statement-breakpoint
CREATE TRIGGER audit_actor_guard BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION foundation_audit_guard();
